Public Class FormPOS

  Sub New()

    InitializeComponent()

    ' This line of code is generated by Data Source Configuration Wizard
    AddHandler TableControl.MakeOrder, AddressOf MakeOrders
  End Sub

  Dim MyListMejaBilyard As New List(Of DaftarMeja)
  Dim MyListMejaResto As New List(Of DaftarMeja)
  Dim MyListMejaBar As New List(Of DaftarMeja)

  Private Sub LoadPanelContent()
    MyListMejaBilyard = DaftarMeja.GetListMejaByIDJenisMeja(1)
    MyListMejaResto = DaftarMeja.GetListMejaByIDJenisMeja(2)
    MyListMejaBar = DaftarMeja.GetListMejaByIDJenisMeja(3)

    For Each Meja As DaftarMeja In MyListMejaBilyard
      Dim MyTable As New TableControl
      With MyTable
        .IDDaftarMeja = Meja.IDDaftarMeja
        .IDJenisMeja = Meja.IDJenisMeja
        .NomorMeja = Meja.NomorMeja
        .Status = Meja.Status
      End With
      BillyardFlowPanel.Controls.Add(MyTable)
      MyTable.Show()
    Next

    For Each Meja As DaftarMeja In MyListMejaResto
      Dim MyTable As New TableControl
      With MyTable
        .IDDaftarMeja = Meja.IDDaftarMeja
        .IDJenisMeja = Meja.IDJenisMeja
        .NomorMeja = Meja.NomorMeja
        .Status = Meja.Status
      End With
      RestoFlowPanel.Controls.Add(MyTable)
      MyTable.Show()
    Next

    For Each Meja As DaftarMeja In MyListMejaBar
      Dim MyTable As New TableControl
      With MyTable
        .IDDaftarMeja = Meja.IDDaftarMeja
        .IDJenisMeja = Meja.IDJenisMeja
        .NomorMeja = Meja.NomorMeja
        .Status = Meja.Status
      End With
      BarFlowPanel.Controls.Add(MyTable)
      MyTable.Show()
    Next

  End Sub

  Private Sub FormPOS_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    MainSplit.CollapsePanel = DevExpress.XtraEditors.SplitCollapsePanel.Panel2
    MainSplit.Collapsed = True


  End Sub

  Private Sub FormPOS_Shown(sender As Object, e As EventArgs) Handles Me.Shown
    LoadPanelContent()
  End Sub

  Private Sub MakeOrders(MyNoMeja As Integer)
    MainSplit.Collapsed = False
    MainTab.SelectedTabPage = MenuPage
  End Sub

  Private Sub DaftarReservasiBtn_Click(sender As Object, e As EventArgs) Handles DaftarReservasiBtn.Click
    FormReservasi.ShowDialog()
  End Sub
End Class