Imports System.Data

Public Class FormReservasi

  Sub New()

    InitializeComponent()
    ' This line of code is generated by Data Source Configuration Wizard

  End Sub

  Dim MyListAnggota As New List(Of Anggota)

  Dim MyListMejaBilliard As New List(Of DaftarMeja)
  Dim MyListMejaResto As New List(Of DaftarMeja)
  Dim MyListMejaBar As New List(Of DaftarMeja)

  Dim MyListReservasiH As New List(Of ReservasiH)
  Dim BindingAnggota As New BindingSource
  Dim BindingReservasi As New BindingSource


  Private Sub FormReservasi_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    MainSplit.Panel1Collapsed = True

    Dim myext As New PenerimaanH(1, Now, 1, 1, 1, Now, Now, "")
    myext.delete()

  End Sub

  Private Sub FormReservasi_Shown(sender As Object, e As EventArgs) Handles Me.Shown
    MyListAnggota = Anggota.GetListAnggotaCombo
    For Each MyAnggota As Anggota In MyListAnggota
      NamaMemberCombo.Properties.Items.Add(MyAnggota.Nama)
    Next
    BindingAnggota.DataSource = MyListAnggota
    NamaMemberCombo.DataBindings.Add("Text", BindingAnggota, "Nama")

    MyListMejaBilliard = DaftarMeja.GetListMejaByIDJenisMeja(1)
    MyListMejaResto = DaftarMeja.GetListMejaByIDJenisMeja(2)
    MyListMejaBar = DaftarMeja.GetListMejaByIDJenisMeja(3)

    MyListReservasiH = ReservasiH.GetReservasiHHariIni

    For Each MyMeja As DaftarMeja In MyListMejaBilliard
      'disini
    Next


    For Each MyReservasi As ReservasiH In MyListReservasiH
      CheckedListReservasi.Items.Add(MyReservasi.Nama)
    Next



    CheckListResto.DataSource = MyListMejaResto
    CheckListResto.ValueMember = "IDDaftarMeja"
    CheckListResto.DisplayMember = "Keterangan"
    CheckListBar.DataSource = MyListMejaBar
    CheckListBar.ValueMember = "IDDaftarMeja"
    CheckListBar.DisplayMember = "Keterangan"



  End Sub

  Private Sub SimpanBtn_Click(sender As Object, e As EventArgs) Handles SimpanBtn.Click

    GridView1.AddNewRow()

    Dim MyReservasiH As New ReservasiH
    With MyReservasiH
      If TamuChk.Checked Then
        .IDAnggota = CType(NamaMemberCombo.SelectedItem, Anggota).IDAnggota
      Else
        .IDAnggota = 0
      End If
      .Nama = NamaTamuTxt.Text
      .UntukTanggal = UntukTanggalReservasi.DateTime

      .AddNew()
    End With


    MainSplit.Panel1Collapsed = True
    MainSplit.Panel2Collapsed = False

  End Sub

  Private Sub BatalBtn_Click(sender As Object, e As EventArgs) Handles BatalBtn.Click
    MainSplit.Panel1Collapsed = True
    MainSplit.Panel2Collapsed = False
  End Sub

  Private Sub ReserveBtn_Click(sender As Object, e As EventArgs) Handles ReserveBtn.Click
    MainSplit.Panel1Collapsed = False
    MainSplit.Panel2Collapsed = True
  End Sub

  Private Sub CheckInBtn_Click(sender As Object, e As EventArgs) Handles CheckInBtn.Click

  End Sub

  Private Sub TamuChk_CheckedChanged(sender As Object, e As EventArgs) Handles TamuChk.CheckedChanged
    If TamuChk.Checked Then
      NamaMemberCombo.Enabled = True
      NamaTamuTxt.Enabled = False
    Else
      NamaMemberCombo.Enabled = False
      NamaTamuTxt.Enabled = True
    End If
  End Sub

  Private Sub NamaMemberCombo_SelectedIndexChanged(sender As Object, e As EventArgs) Handles NamaMemberCombo.SelectedIndexChanged
    Try
      If NamaMemberCombo.Enabled = True Then NamaTamuTxt.Text = NamaMemberCombo.Text
    Catch ex As Exception

    End Try
  End Sub
End Class