Imports System.Data
Imports System.Data.Linq



Public Class FormReservasi

  Sub New()

    InitializeComponent()
    ' This line of code is generated by Data Source Configuration Wizard

    AddHandler ReservasiMejaControl.CheckedTable, AddressOf MyTableChecked

  End Sub

  Dim MyListAnggota As New List(Of Anggota)

  Dim MyListMejaBilliard As New List(Of DaftarMeja)
  Dim MyListMejaResto As New List(Of DaftarMeja)
  Dim MyListMejaBar As New List(Of DaftarMeja)

  Dim MyListReservasiH As New List(Of ReservasiH)
  Dim MyListReservasiD As New List(Of ReservasiD)

  Dim BindingAnggota As New BindingSource
  Dim BindingReservasi As New BindingSource


  Sub MyTableChecked(ByVal IsChecked As Boolean, ByVal MyTableID As Integer, ByVal MyJamMulai As DateTime, MyJamSelesai As DateTime)
    If IsChecked = True Then
      MyListReservasiD.Add(New ReservasiD(0, 0, MyTableID, MyJamMulai, MyJamSelesai))
    Else
      MyListReservasiD.Find(Function(RsvD) RsvD.IDDaftarMeja = MyTableID)
      MyListReservasiD.Remove(MyListReservasiD.Find(Function(RsvD) RsvD.IDDaftarMeja = MyTableID))
    End If

  End Sub

  Private Sub FormReservasi_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    
    MainSplit.Panel1Collapsed = True
    ReserveSplit.Panel2Collapsed = True
  End Sub

  Private Sub FormReservasi_Shown(sender As Object, e As EventArgs) Handles Me.Shown
    MyListAnggota = Anggota.GetListAnggotaCombo

    Dim myNewList = From xList In MyListAnggota
                    Select xList.IDAnggota, xList.Kode, xList.Nama


    NamaMemberCombo.Properties.DataSource = myNewList
    NamaMemberCombo.Properties.DisplayMember = "Nama"
    NamaMemberCombo.Properties.ValueMember = "IDAnggota"
    MyListMejaBilliard = DaftarMeja.GetListMejaByIDJenisMeja(1)
    MyListMejaResto = DaftarMeja.GetListMejaByIDJenisMeja(2)
    MyListMejaBar = DaftarMeja.GetListMejaByIDJenisMeja(3)

    MyListReservasiH = ReservasiH.GetReservasiHHariIni

    FlowBilliard.Controls.Clear()
    For Each MyMeja As DaftarMeja In MyListMejaBilliard
      Dim MyRsvCtrl As New ReservasiMejaControl
      With MyRsvCtrl
        .IDDaftarMeja = MyMeja.IDDaftarMeja
        .NomorMeja = MyMeja.NomorMeja
        .Keterangan = MyMeja.Keterangan
        FlowBilliard.Controls.Add(MyRsvCtrl)
        .Show()
      End With
    Next

    FlowResto.Controls.Clear()
    For Each MyMeja As DaftarMeja In MyListMejaResto
      Dim MyRsvCtrl As New ReservasiMejaControl
      With MyRsvCtrl
        .IDDaftarMeja = MyMeja.IDDaftarMeja
        .NomorMeja = MyMeja.NomorMeja
        .Keterangan = MyMeja.Keterangan
        FlowResto.Controls.Add(MyRsvCtrl)
        .Show()
      End With
    Next

    FlowBar.Controls.Clear()
    For Each MyMeja As DaftarMeja In MyListMejaBar
      Dim MyRsvCtrl As New ReservasiMejaControl
      With MyRsvCtrl
        .IDDaftarMeja = MyMeja.IDDaftarMeja
        .NomorMeja = MyMeja.NomorMeja
        .Keterangan = MyMeja.Keterangan
        FlowBar.Controls.Add(MyRsvCtrl)
        .Show()
      End With
    Next

    CheckedListReservasi.Items.Clear()
    For Each MyReservasi As ReservasiH In MyListReservasiH
      CheckedListReservasi.Items.Add(MyReservasi.Nama)
    Next
    NamaTamuTxt.Text = ""

  End Sub

  Private Sub SimpanBtn_Click(sender As Object, e As EventArgs) Handles SimpanBtn.Click


    Dim MyReservasiH As New ReservasiH
    With MyReservasiH
      If TamuChk.Checked Then
        .IDAnggota = Convert.ToInt64(NamaMemberCombo.EditValue)
      Else
        .IDAnggota = 0
      End If
      .Nama = NamaTamuTxt.Text
      .UntukTanggal = UntukTanggalReservasi.DateTime

      .AddNew(MyListReservasiD)
    End With


    MainSplit.Panel1Collapsed = True
    MainSplit.Panel2Collapsed = False

  End Sub

  Private Sub BatalBtn_Click(sender As Object, e As EventArgs) Handles BatalBtn.Click
    MainSplit.Panel1Collapsed = True
    MainSplit.Panel2Collapsed = False
  End Sub

  Private Sub ReserveBtn_Click(sender As Object, e As EventArgs) Handles ReserveBtn.Click
    MyListReservasiD.Clear()
    MainSplit.Panel1Collapsed = False
    MainSplit.Panel2Collapsed = True
  End Sub

  Private Sub CheckInBtn_Click(sender As Object, e As EventArgs) Handles CheckInBtn.Click

    If CheckedListReservasi.CheckedItems.Count > 0 Then

      ReservasiH.CheckIn(ReservasiH.GetIDReservasiHByNama(CheckedListReservasi.CheckedItems(0).ToString), MyLoggedInPengguna.IDPengguna)

      CheckedListReservasi.Items.Remove(CheckedListReservasi.CheckedItems(0))
    End If
  End Sub

  Private Sub TamuChk_CheckedChanged(sender As Object, e As EventArgs) Handles TamuChk.CheckedChanged
    If TamuChk.Checked Then
      NamaMemberCombo.Enabled = True
      NamaTamuTxt.Enabled = False
    Else
      NamaMemberCombo.Enabled = False
      NamaTamuTxt.Enabled = True
    End If
  End Sub


  Private Sub NamaMemberCombo_EditValueChanged(sender As Object, e As EventArgs) Handles NamaMemberCombo.EditValueChanged
    If NamaMemberCombo.Enabled = True Then
      NamaTamuTxt.Text = NamaMemberCombo.Text
    Else
      NamaTamuTxt.Text = ""
    End If

  End Sub

  Private Sub DetailBtn_Click(sender As Object, e As EventArgs) Handles DetailBtn.Click
    If CheckedListReservasi.CheckedItems.Count > 0 Then
      Me.ReservasiDTableAdapter.FillByIDReservasiH(Me.ReservasiDataset.ReservasiD, ReservasiH.GetIDReservasiHByNama(CheckedListReservasi.CheckedItems(0).ToString))
      ReserveSplit.Panel2Collapsed = False
      ReserveSplit.Panel1Collapsed = True
    End If

  End Sub

  Private Sub BindingNavigatorDeleteItem_Click(sender As Object, e As EventArgs) Handles BindingNavigatorDeleteItem.Click

  End Sub

  Private Sub SaveToolStripButton_Click(sender As Object, e As EventArgs) Handles SaveToolStripButton.Click
    Me.Validate()
    Me.ReservasiDBindingSource.EndEdit()
    Me.ReservasiDTableAdapter.Update(ReservasiDataset)
  End Sub

  Private Sub HomeBtn_Click(sender As Object, e As EventArgs) Handles HomeBtn.Click
    ReserveSplit.Panel2Collapsed = True
    ReserveSplit.Panel1Collapsed = False
  End Sub
End Class