Public Class FormPOS

  Sub New()

    InitializeComponent()

    ' This line of code is generated by Data Source Configuration Wizard
    AddHandler TableControl.MakeOrder, AddressOf MakeOrders
  End Sub

  Dim MyMejaBillyardDataTable As DataTable

  Sub LoadPanelContent()
    
    For Each MyRow As DataRow In MyMejaBillyardDataTable.Rows
      Dim MyTable As New TableControl
      With MyTable
        .IDDaftarMeja = Convert.ToInt32(MyRow.Item(0))
        .IDJenisMeja = Convert.ToInt32(MyRow(1))
        .NomorMeja = Convert.ToInt32(MyRow.Item(2))
        .Status = 0
      End With
      BillyardFlowPanel.Controls.Add(MyTable)
      MyTable.Show()
    Next
  End Sub

  Private Sub FormPOS_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    'TODO: This line of code loads data into the 'DataSetDaftarMeja1.DaftarMeja' table. You can move, or remove it, as needed.
    MainSplit.CollapsePanel = DevExpress.XtraEditors.SplitCollapsePanel.Panel2
    MainSplit.Collapsed = True

    MyMejaBillyardDataTable = DataAccess.ExecuteQueryTable("Exec Dtm_SelectByJenisMeja 1")
    LoadPanelContent()

  End Sub

  Private Sub MakeOrders(MyNoMeja As Integer)
    MainSplit.Collapsed = False
    MainTab.SelectedTabPage = MenuPage
  End Sub


End Class