Public Class FormPOS

  Sub New()

    InitializeComponent()

    ' This line of code is generated by Data Source Configuration Wizard
  End Sub

  Sub LoadPanelContent()

  End Sub

  Private Sub FormPOS_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    'TODO: This line of code loads data into the 'DataSetDaftarMeja1.DaftarMeja' table. You can move, or remove it, as needed.


  End Sub

End Class